# version: '3.8'

# services:
#   api:
#     build: ./app
#     volumes:
#       - .:/code
#     ports:
#       - '80:80'
#     environment:
#       - DB_URL=mongodb://db/myTestDB
#     depends_on:
#       - db
#   db:
#     image: mongo
#     ports:
#       - 27017:27017
#     volumes:
#       - taskdb:/data/db


# volumes:
#     taskdb: